# This rule is not used by the project demo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cmp.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: stack-editor-role
rules:
- apiGroups:
  - cmp.example.com
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cmp.example.com
  resources:
  - stacks/status
  verbs:
  - get
